# Generated by Django 5.2.5 on 2025-08-16 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_wastage'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='extra_ice',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
    ]
