# Generated by Django 5.2.5 on 2025-09-13 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stock_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('electricity', 'Electricity'), ('salary', 'Salary'), ('food', 'Food/Tea'), ('services', 'Services'), ('petrol', 'Petrol'), ('other', 'Other')], default='other', max_length=50),
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
