# Generated by Django 5.2.5 on 2025-09-13 19:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_expense_date'),
        ('sales', '0002_retailsale_added_water_wholesalesale_added_water_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='shop',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='supplier',
        ),
        migrations.AddField(
            model_name='retailsale',
            name='shift',
            field=models.CharField(blank=True, choices=[('morning', 'Morning'), ('evening', 'Evening')], max_length=20, null=True),
        ),
        migrations.AddIndex(
            model_name='retailsale',
            index=models.Index(fields=['date_time'], name='sales_retai_date_ti_3b2b35_idx'),
        ),
        migrations.AddIndex(
            model_name='retailsale',
            index=models.Index(fields=['payment_status'], name='sales_retai_payment_b4078d_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalesale',
            index=models.Index(fields=['date_time'], name='sales_whole_date_ti_3db3c2_idx'),
        ),
        migrations.AddIndex(
            model_name='wholesalesale',
            index=models.Index(fields=['payment_status'], name='sales_whole_payment_11edfc_idx'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
